# Generated by Django 2.0.2 on 2018-02-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='img_url',
            field=models.ImageField(default='media/default.png', upload_to='treasure_images'),
        ),
    ]
