# Generated by Django 2.0.2 on 2018-02-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180214_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasure',
            old_name='img_url',
            new_name='image',
        ),
    ]
