# Generated by Django 2.0.2 on 2018-02-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180214_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoOrcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_postal', models.CharField(max_length=100)),
                ('largura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprimento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=250)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Divisao')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Estilo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoImovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imovel', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoorcamento',
            name='tipo_imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TipoImovel'),
        ),
    ]
