# Generated by Django 2.0.2 on 2018-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_pedidoorcamento_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treasure',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
