# Generated by Django 2.0.2 on 2018-02-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20180219_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='imagem',
            field=models.ImageField(default='media/default.png', upload_to='treasure_images'),
        ),
    ]
