# Generated by Django 2.0.2 on 2018-03-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_projetos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
