# Generated by Django 2.0.2 on 2018-03-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_projetos_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
