# Generated by Django 2.0.2 on 2018-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_projetos_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estilo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
