# Generated by Django 2.0.2 on 2018-03-05 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_projetos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
