# Generated by Django 2.0.2 on 2018-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_projetos_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='tags',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
