# Generated by Django 2.0.2 on 2018-03-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_projetos_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoorcamento',
            name='user',
        ),
    ]
