# Generated by Django 2.0.2 on 2018-03-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20180309_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoorcamento',
            name='email',
            field=models.EmailField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
