# Generated by Django 2.0.2 on 2018-03-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_auto_20180314_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='area',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
