# Generated by Django 2.0.2 on 2018-03-16 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_projetos_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoorcamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
