# Generated by Django 2.0.2 on 2018-03-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_pedidoorcamento_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotosprojeto',
            name='descricao',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
