# Generated by Django 2.0.2 on 2018-04-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_fotosprojeto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoOrcamentoProjetoExistente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=250)),
                ('cod_postal', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.EmailField(max_length=250)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Categoria')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Divisao')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Estilo')),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Projetos')),
                ('tipo_imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.TipoImovel')),
            ],
        ),
        migrations.AlterField(
            model_name='fotosprojeto',
            name='descricao',
            field=models.CharField(max_length=250),
        ),
    ]
